package com.example.domain

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable
import com.example.util.logger

@DynamoDBTable(tableName = "item-table-dev")
data class Item constructor(@DynamoDBHashKey(attributeName = "id")
                            @DynamoDBAutoGeneratedKey var id: String?,
//                @DynamoDBRangeKey(attributeName = "name")
                            var name: String,
                            @DynamoDBAttribute(attributeName = "description") var description: String) {

    constructor() : this(null, "", "")
    constructor(name: String, description: String) : this(null, name, description)

    companion object {
        private val LOG = logger()
    }
}